version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  node:
    build: ./
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

volumes:
  postgres_data:

