version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - my_network

  node:
    image: node:latest
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - my_network

    command: npm start


volumes:
  postgres_data:

networks:
  my_network: