version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: node-test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - my_network

  node:
    image: node:latest
    ports:
      - "3000:3000"
    networks:
      - my_network
    command: npm start


volumes:
  postgres_data:

networks:
  my_network: